version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

commands:
  build:
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            sudo pip install poetry
            poetry install --system
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
  test:
    steps:
      - run:
          name: run Tests
          command: |
            make test-coverage
            poetry run coverage xml
      - store_artifacts:
          path: coverage.xml
      - codecov/upload:
          file: coverage.xml
          flags: backend

  publish:
    steps:
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: publish package
          command: |
            make publish

jobs:
  test:
    working_directory: ~/covid
    docker:
      - image: circleci/python:3.8
    steps:
      - build
      - test

  publish:
    working_directory: ~/covid
    docker:
      - image: circleci/python:3.8
    steps:
      - build
      - publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test
      - publish:
          context: pypi
          requires:
            - test
          filters:
            branches:
              only: master
